services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: workout
      POSTGRES_USER: workout
      POSTGRES_DB: workout_db
    ports:
      - "5432:5432"
    volumes:
      - workout_pgdata:/var/lib/postgresql/data

volumes:
  workout_pgdata:      

