"""init_db

Revision ID: 955e871a3ff5
Revises: 5a63024f5cb6
Create Date: 2025-08-31 19:23:25.411506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '955e871a3ff5'
down_revision: Union[str, Sequence[str], None] = '5a63024f5cb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('atletas', 'cpf',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=11),
               existing_nullable=False)
    op.alter_column('categorias', 'nome',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('centros_treinamento', 'nome',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('centros_treinamento', 'nome',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('categorias', 'nome',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('atletas', 'cpf',
               existing_type=sa.String(length=11),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
